### PR TITLE
Fixed product market maker overflow issue

### PR DESCRIPTION
**Pull request by cag**
@fvictorio This should resolve the overflow issues.

### CODE REVIEW

**Comment by fvictorio** [comment]
Awesome! I'll try to create a market maker with 10 outcomes using this branch and let you know.

**Comment by fvictorio** [comment]
I get an error when using 9/10 outcomes:

```
Runtime Error: revert
Revert reason: create2 failed
```

Doesn't happen for 6 or less. I didn't test it with 7 or 8 outcomes so I don't know exactly at which point it stops working, but I can find out if it can help you.

I tested this in ganache so I don't have a link to the failing transaction, but can do it if you want.

**Comment by cag** [comment]
Can you give me any more info, like an example of the params you used? I will try to write a test case for this.

**Comment by fvictorio** [comment]
I was reproducing it to send you the transaction but it worked on Rinkeby (I was using ganache before). But from what I can tell from the `package.json` and `truffle.js`, you are running the tests on ganache, aren't you?

**Comment by fvictorio** [comment]
These are the arguments that are triggering the error in ganache:

```
salt: 79932
conditionalTokens: 0xD86C8F0327494034F60e25074420BcCF560D5610
collateralToken: 0x9561C133DD8580860B6b7E504bC5Aa500f0f06a7
conditionIds: ["0xc64342d07a96343f150eab7da7d653af79431b0c8e5af72a898b0d99eb87112f"]
gas: 4% (expressed over 1e18)
initialFunding: 0
distributionHint: []
```

**Comment by fvictorio** [comment]
Wait, it worked on Rinkeby because I didn't use the new factory :man_facepalming: (I did use the new version in Ganache). I will test it properly now.

**Comment by fvictorio** [comment]
Ok, now I really can confirm it works on Rinkeby for 10 outcomes ([created market](http://localhost:3000/#/0xD44F124d42D1E5b50ae9E3BD1B9957464A256224)). I'll look into the ganache issue some other time.

**Comment by cag** [comment]
Hmm, that is weird. I wonder if it has to do with the version of Ganache or something. Anyway, I'll publish this, but if you get any more info about this, I've created an issue to track the development of the revert on Ganache issue.

**Pull request merged**
